#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

COMPOSE=${COMPOSE:-docker compose}
REALITY_PORT_POOL=${REALITY_PORT_POOL:-"8444 2053 2083"}
AWG_PORT_POOL=${AWG_PORT_POOL:-"51888 51889 51890 51891"}

need() {
  command -v "$1" >/dev/null || {
    echo "missing required command: $1" >&2
    exit 1
  }
}

port_free_tcp() {
  ! ss -tln "sport = :$1" | awk 'NR>1{found=1} END{exit found?0:1}'
}

port_free_udp() {
  ! ss -uln "sport = :$1" | awk 'NR>1{found=1} END{exit found?0:1}'
}

pick_tcp_port() {
  for p in $REALITY_PORT_POOL; do
    if port_free_tcp "$p"; then echo "$p"; return; fi
  done
  echo "no free REALITY TCP port in pool: $REALITY_PORT_POOL" >&2
  exit 1
}

pick_udp_port() {
  for p in $AWG_PORT_POOL; do
    if port_free_udp "$p"; then echo "$p"; return; fi
  done
  echo "no free AWG UDP port in pool: $AWG_PORT_POOL" >&2
  exit 1
}

detect_ip() {
  if [ -n "${EGRESS_IP:-}" ]; then echo "$EGRESS_IP"; return; fi
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' RETURN
  for url in https://api.ipify.org https://ifconfig.co/ip https://ipinfo.io/ip; do
    curl -4fsS --max-time 4 "$url" >>"$tmp" 2>/dev/null || true
    printf '\n' >>"$tmp"
  done
  ip=$(awk 'NF && $1 ~ /^[0-9.]+$/ {c[$1]++} END{for (i in c) if (c[i] >= 2) {print i; exit}}' "$tmp")
  if [ -n "$ip" ]; then echo "$ip"; return; fi
  if [ -n "${WAN_IF:-}" ]; then
    ip -4 addr show dev "$WAN_IF" | awk '/inet /{sub(/\/.*/, "", $2); print $2; exit}'
    return
  fi
  hostname -I | awk '{print $1}'
}

first_host() {
  python3 - "$1" <<'PY'
import ipaddress, sys
net=ipaddress.ip_network(sys.argv[1], strict=False)
print(next(net.hosts()))
PY
}

write_env() {
  [ -f .env ] && cp .env ".env.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp .env.example .env
  xr=${XRAY_PORT:-$(pick_tcp_port)}
  awg=${AWG_PORT:-$(pick_udp_port)}
  subnet=${AWG_SUBNET:-10.13.13.0/24}
  gateway=${AWG_GATEWAY:-$(first_host "$subnet")}
  egress=$(detect_ip)
  camouflage=${CAMOUFLAGE_DOMAIN:-}
  python3 - "$xr" "$awg" "$subnet" "$gateway" "$egress" "$camouflage" <<'PY'
import sys
path=".env"
xr, awg, subnet, gateway, egress, camouflage = sys.argv[1:]
repl={
 "XRAY_PORT": xr,
 "AWG_PORT": awg,
 "AWG_SUBNET": subnet,
 "AWG_GATEWAY": gateway,
 "EGRESS_IP": egress,
 "CAMOUFLAGE_DOMAIN": camouflage,
}
lines=[]
for line in open(path):
    if "=" in line and not line.startswith("#"):
        k=line.split("=",1)[0]
        if k in repl:
            line=f"{k}={repl[k]}\n"
    lines.append(line)
open(path,"w").writelines(lines)
PY
}

verify_dest_hint() {
  domain=$(awk -F= '$1=="CAMOUFLAGE_DOMAIN"{print $2}' .env | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
  dest=$(awk -F= '$1=="REALITY_DEST"{print $2}' .env)
  case "$domain" in
    ""|example.com|example.org)
      echo "error: refusing placeholder CAMOUFLAGE_DOMAIN; set a real TLS1.3 domain" >&2
      exit 1
      ;;
  esac
  case "$dest" in
    *:443)
      host=${dest%:*}
      echo | openssl s_client -tls1_3 -alpn h2 -servername "$domain" -connect "$host:443" >/dev/null 2>&1 || {
        echo "warning: REALITY_DEST TLS1.3+h2 probe failed for $dest; internal self-steal dest may be generated by compose" >&2
      }
      ;;
  esac
}

apply_nft_optional() {
  [ "${APPLY_NFT:-0}" = "1" ] || return 0
  need nft
  nft list ruleset >"worker-state/nft-backup.$(date -u +%Y%m%dT%H%M%SZ).txt" 2>/dev/null || true
  nft add table inet trafficwrapper_worker 2>/dev/null || true
  nft 'add chain inet trafficwrapper_worker input { type filter hook input priority 20; policy accept; }' 2>/dev/null || true
  xray_port=$(awk -F= '$1=="XRAY_PORT"{print $2}' .env)
  awg_port=$(awk -F= '$1=="AWG_PORT"{print $2}' .env)
  nft add rule inet trafficwrapper_worker input tcp dport "$xray_port" counter accept 2>/dev/null || true
  nft add rule inet trafficwrapper_worker input udp dport "$awg_port" counter accept 2>/dev/null || true
}

need docker
need ss
need curl
need python3
need openssl

mkdir -p worker-state
write_env
verify_dest_hint
apply_nft_optional
$COMPOSE up -d --build
$COMPOSE ps
